run:
  tests: false

linters-settings:
  funlen:
    lines: 150
    statements: 80
  goimports:
    local-prefixes: github.com/gardashvs/home-work/hw12_13_14_15_calendar

linters:
  disable-all: false
  enable-all: false
  enable:
    - gofumpt